{{- $password := (index .Values "postgresql" "auth" "password") -}}
{{- $uri := print "postgres://" .Values.postgresql.auth.username  ":" .Values.postgresql.auth.password "@" (include "postgresql.primary.fullname" .Subcharts.postgresql) ":" (include "postgresql.service.port" .Subcharts.postgresql) "/" .Values.postgresql.auth.database "?sslmode=disable" -}}
apiVersion: v1
data:
  postgres-password: "{{ $password | b64enc }}"
  uri: "{{ $uri | b64enc }}"
kind: Secret
metadata:
  name: coder-postgresql-creds
type: Opaque