# SPDX-FileCopyrightText: © 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: kubernetes-resource-manager
description: A Helm chart for Kubernetes
home: "https://github.com/scc-digitalhub/digitalhub/tree/main/charts/kubernetes-resource-manager"
type: application
version: 0.2.8
appVersion: "1.2.3"
maintainers:
  - name: ffais
    url: https://github.com/ffais
  - name: calcagiara
    url: https://github.com/Calcagiara
