{{- if (index .Values "oauth2-proxy" "enabled") }}
{{- range $key, $value := (index .Values "oauth2-proxy" "apps") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-proxy-{{ $value.name }}
  # annotations:
  #   "helm.sh/hook": pre-install
  #   "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation,hook-failed
  #   "helm.sh/hook-weight": "1"
data:
  OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:4180
  OAUTH2_PROXY_EMAIL_DOMAINS: "*"
  OAUTH2_PROXY_COOKIE_SECURE: "true"
  OAUTH2_PROXY_COOKIE_SECRET: {{ randAlphaNum 32 | quote }}
  OAUTH2_PROXY_UPSTREAMS: "http://{{ $value.service.name }}:{{ $value.service.port }}"
  OAUTH2_PROXY_REDIRECT_URL: {{ $value.redirectUrl }}
  OAUTH2_PROXY_OIDC_ISSUER_URL: {{ $value.oidcIssuerUrl }}
  OAUTH2_PROXY_PROVIDER: oidc
  OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
  OAUTH2_PROXY_REVERSE_PROXY: "true"
---
{{- end }}
{{- end }}
