{{- if (index .Values "oauth2-proxy" "enabled") }}
{{- range $key, $value := (index .Values "oauth2-proxy" "apps") }}
{{- if $value.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth-proxy-{{ $value.name }}
  labels:
    app: oauth-proxy-{{ $value.name }}
  annotations:
    {{- toYaml $value.ingress.annotations | nindent 4 }}
spec:
  {{- if $value.ingress.ingressClassName }}
  {{/* If this is set to an empty string it fails validation on K8s */}}
  ingressClassName: {{ $value.ingress.ingressClassName | quote }}
  {{- end }}
  rules:
  {{- if $value.ingress.hosts  }}
  {{- range $value.ingress.hosts }}
    - host: {{ tpl . $ | quote }}
      http:
        paths:
          - path: {{ $value.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: oauth-proxy-{{ $value.name }}
                port:
                  number: 4180
  {{- end }}
  {{- end }}
  {{- with $value.ingress.tls }}
  tls:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- end }}
{{- end }}