{{- if (index .Values "oauth2-proxy" "enabled") }}
{{- range $key, $value := (index .Values "oauth2-proxy" "apps") }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oauth-proxy-{{ $value.name }}
  name: oauth-proxy-{{ $value.name }}
spec:
  type: ClusterIP
  selector:
    app: oauth-proxy-{{ $value.name }}
  ports:
  - name: http-oauthproxy
    port: 4180
---
{{- end }}
{{- end }}