apiVersion: v1
data:
  viewer-pod-template.json: |-
    {
        "spec": {
            "serviceAccountName": "kubeflow-pipelines-viewer",
            "containers": [
            {
              "env": [
                {
                  "name": "AWS_ACCESS_KEY_ID",
                  "valueFrom": {
                    "secretKeyRef": {
                    {{- if .Values.s3.externalSecret.secretName }}
                      "name": "{{ .Values.s3.externalSecret.secretName }}",
                      "key": "{{ .Values.s3.externalSecret.accessKeyField }}"
                    {{- else }}
                      "name": "mlpipeline-s3-artifact",
                      "key": "accesskey"
                    {{- end }}
                    }
                  }
                },
                {
                  "name": "AWS_SECRET_ACCESS_KEY",
                  "valueFrom": {
                    "secretKeyRef": {
                    {{- if .Values.s3.externalSecret.secretName }}
                      "name": "{{ .Values.s3.externalSecret.secretName }}",
                      "key": "{{ .Values.s3.externalSecret.secretKeyField }}"
                    {{- else }}
                      "name": "mlpipeline-s3-artifact",
                      "key": "secretkey"
                    {{- end }}
                    }
                  }
                }
              ]
            }
          ]
        }
    }
kind: ConfigMap
metadata:
  labels:
    application-crd-id: kubeflow-pipelines
  name: ml-pipeline-ui-configmap
