apiVersion: v1
data:
  s3ServiceHost: {{ include "kubeflow-pipelines.s3-pipeline.service.url" . }}
  s3ServicePort: "{{ .Values.s3.endpointPort }}"
  ConMaxLifeTime: 120s
  DEFAULT_CACHE_STALENESS: ""
  LOG_LEVEL: info
  MAXIMUM_CACHE_STALENESS: ""
  appName: pipeline
  appVersion: 2.3.0
  autoUpdatePipelineDefaultVersion: "false"
  bucketName: "{{ .Values.s3.bucket }}"
  cacheDb: cachedb
  cacheImage: busybox
  cacheNodeRestrictions: "false"
  cronScheduleTimezone: UTC
  dbHost: {{ .Values.db.host }}
  dbPort: {{ .Values.db.port | quote }}
  dbType: {{ .Values.db.type }}
  defaultPipelineRoot: ""
  mlmdDb: {{ .Values.db.mlmdDb }}
  mysqlHost: {{ .Values.db.host }}
  mysqlPort: {{ .Values.db.port | quote }}
  pipelineDb: {{ .Values.db.pipelineDb }}
  warning: |
    1. Do not use kubectl to edit this configmap, because some values are used
    during kustomize build. Instead, change the configmap and apply the entire
    kustomize manifests again.
    2. After updating the configmap, some deployments may need to be restarted
    until the changes take effect. A quick way to restart all deployments in a
    namespace: `kubectl rollout restart deployment -n <your-namespace>`.
kind: ConfigMap
metadata:
  labels:
    application-crd-id: kubeflow-pipelines
  name: pipeline-install-config
