apiVersion: v1
data:
  artifactRepository: |
    archiveLogs: true
    s3:
      endpoint: "{{ include "kubeflow-pipelines.s3-pipeline.service.url" . }}:{{ .Values.s3.endpointPort }}"
      bucket: "{{ .Values.s3.bucket }}"
      keyFormat: "{{`artifacts/{{workflow.name}}/{{workflow.creationTimestamp.Y}}/{{workflow.creationTimestamp.m}}/{{workflow.creationTimestamp.d}}/{{pod.name}}`}}"
      insecure: true
      accessKeySecret:
      {{- if .Values.s3.externalSecret.secretName }}
        name: {{ .Values.s3.externalSecret.secretName }}
        key: {{ .Values.s3.externalSecret.accessKeyField }}
      {{- else }}
        name: mlpipeline-s3-artifact
        key: accesskey
      {{- end }}
      secretKeySecret:
      {{- if .Values.s3.externalSecret.secretName }}
        name: {{ .Values.s3.externalSecret.secretName }}
        key: {{ .Values.s3.externalSecret.secretKeyField }}
      {{- else }}
        name: mlpipeline-s3-artifact
        key: secretkey
      {{- end }}
  executor: |
    imagePullPolicy: IfNotPresent
kind: ConfigMap
metadata:
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|default|workflow-controller-configmap'
  labels:
    application-crd-id: kubeflow-pipelines
  name: workflow-controller-configmap
