apiVersion: v1
kind: ConfigMap
metadata:
  name: digitalhub-common-env
data:
  S3_BUCKET_NAME: {{ .Values.minio.bucket }}
  S3_ENDPOINT_URL: "{{ .Values.minio.protocol }}://{{ .Values.minio.endpoint }}:{{ .Values.minio.endpointPort }}"
  POSTGRES_HOST: {{ .Values.postgres.host }}
  POSTGRES_PORT: {{ .Values.postgres.port | quote }}
  POSTGRES_DATABASE: {{ .Values.postgres.database }}
  POSTGRES_SCHEMA: {{ .Values.postgres.schema }}
  S3_BUCKET_NAME: {{ .Values.minio.bucket }}
  KFP_ENDPOINT: {{ .Values.kfp.endpoint }}
  DHCORE_WORKFLOW_IMAGE: {{ .Values.runtime.kfp.image }}:{{ .Values.runtime.kfp.tag }}
  KFP_ENDPOINT: http://ml-pipeline:8888
  DHCORE_ENDPOINT: "{{ include "core.endpoint" . }}"
  DHCORE_ISSUER: "{{ include "core.endpoint" . }}"
