apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "core.fullname" . }}
data:
  DH_ENDPOINT: "http://{{ include "core.fullname" . }}:{{ .Values.service.port }}"
  DH_S3_ENDPOINT_URL: "{{ .Values.minio.endpoint }}:{{ index .Values.minio.endpointPort }}"
  DH_S3_BUCKET_NAME: core
  DH_POSTGRES_HOST: "database-postgres-cluster"
  DH_POSTGRES_PORT: "5432"
  DH_POSTGRES_DATABASE: digitalhub
  DH_POSTGRES_SCHEMA: public
  K8S_NAMESPACE: {{ .Release.Namespace }}
  JDBC_URL: "jdbc:postgresql://core-postgres-cluster:5432/core"
  JDBC_DRIVER: org.postgresql.Driver
  JDBC_DIALECT: org.hibernate.dialect.PostgreSQLDialect
  JDBC_TABLE: "classpath:db/schema-postgres.sql"
  H2_CONSOLE: "false"
  DH_CONFIG_COMMON_SECRETS: digitalhub-common-creds
  DH_CONFIG_COMMON_MAPS: digitalhub-common-env
  RUNTIME_NEFERTEM_IMAGE: {{ .Values.runtime.nefertem.image }}:{{ .Values.runtime.nefertem.tag }}
  RUNTIME_DBT_IMAGE: {{ .Values.runtime.dbt.image }}:{{ .Values.runtime.dbt.tag }}
  RUNTIME_MLRUN_IMAGE: {{ .Values.runtime.mlrun.image }}:{{ .Values.runtime.mlrun.tag }}
  {{- if .Values.events.enabled }}
  ENABLE_EVENTS: {{ .Values.events.enabled | quote }} 
  {{- if .Values.events.rabbitmq.enabled }}
  RABBITMQ_ENABLE: {{ .Values.events.rabbitmq.enabled }}
  RABBITMQ_HOST: {{ .Values.events.rabbitmq.host }}
  RABBITMQ_PORT: {{ .Values.events.rabbitmq.port | quote }}
  RABBITMQ_VHOST: {{ .Values.events.rabbitmq.vhost }}
  RABBITMQ_QUEUE: {{ .Values.events.rabbitmq.queue }}
  RABBITMQ_TOPIC: {{ .Values.events.rabbitmq.topic }}
  RABBITMQ_ROUTING_KEY: {{ .Values.events.rabbitmq.routingKey }}
{{- end }}
{{- end }}
{{- if .Values.solr.enabled }}
  ENABLE_SOLR: {{ .Values.solr.enabled | quote }}
  SOLR_URL: {{ .Values.solr.url }}
  SOLR_COLLECTION: {{ .Values.solr.collection }}
{{- end }}