apiVersion: v1
kind: ConfigMap
metadata:
  name: digitalhub-common-env
data:
  S3_BUCKET_NAME: {{ .Values.minio.bucketName }}
  S3_ENDPOINT_URL: "http://minio:{{ .Values.minio.endpointPort }}"
  DIGITALHUB_CORE_ENDPOINT: "http://{{ include "core.fullname" . }}:{{ .Values.service.port }}"
  DIGITALHUB_KRM_ENDPOINT: "http://{{ .Release.Name }}-kubernetes-resource-manager:{{ .Values.krm.port }}"
  POSTGRES_HOST: {{ .Values.postgres.host }}
  POSTGRES_PORT: {{ .Values.postgres.port | quote }}
  POSTGRES_DATABASE: {{ .Values.postgres.database }}
  POSTGRES_SCHEMA: {{ .Values.postgres.schema }}
  S3_BUCKET_NAME: {{ .Values.minio.bucketName }}
  KFP_ENDPOINT: {{ .Values.kfp.endpoint }}
  DIGITALHUB_CORE_WORKFLOW_IMAGE: {{ .Values.runtime.kfp.image }}
  KFP_ENDPOINT: http://ml-pipeline:8888
