apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "core.fullname" . }}
  labels:
    {{- include "core.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "core.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "core.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "core.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DH_S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: rootUser
            - name: DH_S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: rootPassword
            - name: DH_AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: rootUser
            - name: DH_AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: rootPassword
            - name: DH_POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: digitalhub-owner-user.database-postgres-cluster.credentials.postgresql.acid.zalan.do
                  key: username
            - name: DH_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: digitalhub-owner-user.database-postgres-cluster.credentials.postgresql.acid.zalan.do
                  key: password
            - name: JDBC_USER
              valueFrom:
                secretKeyRef:
                  name: coreuser.core-postgres-cluster.credentials.postgresql.acid.zalan.do
                  key: username
            - name: JDBC_PASS
              valueFrom:
                secretKeyRef:
                  name: coreuser.core-postgres-cluster.credentials.postgresql.acid.zalan.do
                  key: password
            {{- if and .Values.events.enabled .Values.events.rabbitmq.enabled }}
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.events.rabbitmq.credentials.existingSecret.name | default (printf "%s-rabbitmq-creds" (include "core.fullname" .)) }}
                  key: {{ .Values.events.rabbitmq.credentials.existingSecret.usernameKey | default "username" }}
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.events.rabbitmq.credentials.existingSecret.name | default (printf "%s-rabbitmq-creds" (include "core.fullname" .)) }}
                  key: {{ .Values.events.rabbitmq.credentials.existingSecret.passwordKey | default "password" }}
            {{- end }}
            {{- if .Values.oidc.enabled }}
            - name: DH_AUTH_OIDC_CLIENT_ID
              {{- if .Values.oidc.audience.externalSecret.name  }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.oidc.audience.externalSecret.name }}
                  key: {{ .Values.oidc.audience.externalSecret.key }}
              {{- else}}
              value: {{ .Values.oidc.audience.clientId }}
              {{- end }}
            {{- end }}
          envFrom:
          - configMapRef:
              name: {{ include "core.fullname" . }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
