apiVersion: v1
kind: Secret
metadata:
  name: {{ include "core.fullname" . }}-rabbitmq-creds
type: Opaque
data:
  username: {{ .Values.events.rabbitmq.credentials.username | b64enc | quote }}
  password: {{ .Values.events.rabbitmq.credentials.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: core-auth-creds
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": hook-failed
type: Opaque
data:
  clientId: {{ randAlphaNum 24 | nospace | b64enc }}
  clientSecret: {{ randAlphaNum 24 | nospace | b64enc }}
