# SPDX-FileCopyrightText: © 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: Apache-2.0

{{ if not (and .Values.coreAuthCreds.existingSecret.secretName .Values.coreAuthCreds.existingSecret.clientIdKey .Values.coreAuthCreds.existingSecret.clientSecretKey) -}}
apiVersion: v1
kind: Secret
metadata:
  name: core-auth-creds
type: Opaque
data:
  clientId: {{ .Values.coreAuthCreds.clientId | b64enc }}
  clientSecret: {{ .Values.coreAuthCreds.clientSecret | b64enc }}
{{- end }}
