repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.14.2
    hooks:
      - id: helm-docs
        args:
          - --chart-search-root=charts
          - --template-files=README.md.gotmpl
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.14.2
    hooks:
      - id: helm-docs
        alias: helm-docs-configuration
        args:
          - --chart-search-root=charts/digitalhub
          - --template-files=CONFIGURATION.md.gotmpl
          - --output-file=CONFIGURATION.md
