apiVersion: v2
name: core
description: Core backend application for DigitalHub.
type: application
version: 0.2.19
appVersion: "0.8.0"
maintainers:
  - name: ffais
    url: https://github.com/ffais
  - name: calcagiara
    url: https://github.com/Calcagiara
