apiVersion: v2
name: core
description: A Helm chart for Kubernetes
type: application
version: 0.1.2
appVersion: "0.0.29"
maintainers:
  - name: scc-digitalhub
    url: https://github.com/scc-digitalhub
