apiVersion: v2
name: core
description: Core backend application for DigitalHub.
type: application
version: 0.1.10
appVersion: "0.3.0"
maintainers:
  - name: scc-digitalhub
    url: https://github.com/scc-digitalhub
