apiVersion: v2
name: digitalhub
description: The Digital Hub is an open-source platform for interoperability of data and services, built by integrating several open-source projects to manage, elaborate, expose and serve data through modern standards.
type: application
maintainers:
  - name: ffais
    url: https://github.com/ffais
  - name: calcagiara
    url: https://github.com/Calcagiara
version: "0.4.0-beta9"
appVersion: "0.4.0"
dependencies:
- name: apigw-operator
  version: "0.1.4"
  repository: https://scc-digitalhub.github.io/digitalhub/
  condition: apigw-operator.enabled
- name: coder
  version: "0.1.0"
  repository: https://scc-digitalhub.github.io/digitalhub/
  condition: coder.enabled
- name: core
  version: "0.1.15"
  repository: https://scc-digitalhub.github.io/digitalhub/
  condition: core.enabled
# - name: kubernetes-resource-manager
#   version: "0.1.9"
#   repository: https://scc-digitalhub.github.io/digitalhub/
#   condition: kubernetes-resource-manager.enabled
- name: dremio-rest-server-operator
  version: "0.1.3"
  repository: https://scc-digitalhub.github.io/digitalhub/
  condition: dremio-rest-server-operator.enabled
- name: docker-registry
  version: "2.2.2"
  repository: "https://helm.twun.io"
  condition: docker-registry.enabled
- name: ext-postgres-operator
  version: "1.2.4"
  repository: https://scc-digitalhub.github.io/digitalhub/
  condition: ext-postgres-operator.enabled
- name: grafana
  version: "7.0.3"
  repository: "https://grafana.github.io/helm-charts"
  condition: grafana.enabled
- name: minio
  repository: "https://charts.min.io/"
  version: "5.1.0"
  condition: minio.enabled
- name: mlrun-ce
  version: "0.6.3-dh-v0.3.5"
  repository: https://scc-digitalhub.github.io/digitalhub/
  condition: mlrun-ce.enabled
- name: mysql-operator
  version: "2.1.2"
  repository: https://mysql.github.io/mysql-operator/
  condition: mysql-operator.enabled
- name: nakamasato-mysql-operator
  version: "v0.3.3"
  repository: https://scc-digitalhub.github.io/digitalhub/
  condition: nakamasato-mysql-operator.enabled
- name: postgres-operator
  version: "1.11.0"
  repository: "https://opensource.zalando.com/postgres-operator/charts/postgres-operator"
  condition: postgres-operator.enabled
  tags:
    - operator
- name: postgrest-operator
  version: "0.1.2"
  repository: https://scc-digitalhub.github.io/digitalhub/
  condition: postgrest-operator.enabled
- name: template-controller
  version: "0.2.5"
  repository: https://kluctl.github.io/charts
  condition: template-controller.enabled
  tags:
    - operator
- name: solr-operator
  version: "0.8.1"
  repository: https://solr.apache.org/charts
  condition: solr-operator.enabled
  tags:
    - operator
- name: solr
  version: "0.8.1"
  repository: https://solr.apache.org/charts
  condition: solr.enabled
