{{- if .Values.pipelines.enabled -}}
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: ml-pipeline-ui
    application-crd-id: kubeflow-pipelines
  name: ml-pipeline-ui
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
    {{- if eq .Values.pipelines.service.type "NodePort" }}
    nodePort: 30100
    {{- end }}
  selector:
    app: ml-pipeline-ui
    application-crd-id: kubeflow-pipelines
  sessionAffinity: None
  type: {{ .Values.pipelines.service.type }}
{{- end -}}
