#  deployment --
deployment:
  #  deployment.image --
  image:
    #  deployment.image.pullPolicy --
    pullPolicy: IfNotPresent
  #  deployment.kubeRbacProxy --
  kubeRbacProxy:
    #  deployment.kubeRbacProxy.args --
    args:
    - "--secure-listen-address=0.0.0.0:8443"
    - "--upstream=http://127.0.0.1:8080/"
    - "--logtostderr=true"
    - "--v=0"
    #  deployment.kubeRbacProxy.image --
    image:
      #  deployment.kubeRbacProxy.image.repository --
      repository: gcr.io/kubebuilder/kube-rbac-proxy
      #  deployment.kubeRbacProxy.image.tag --
      tag: v0.13.1
    #  deployment.kubeRbacProxy.name --
    name: kube-rbac-proxy
    #  deployment.kubeRbacProxy.ports --
    ports:
      #  deployment.kubeRbacProxy.ports.containerPort --
      containerPort: 8443
    #  deployment.kubeRbacProxy.resources --
    resources:
      #  deployment.kubeRbacProxy.resources.limits --
      limits:
        #  deployment.kubeRbacProxy.resources.limits.cpu --
        cpu: 500m
        #  deployment.kubeRbacProxy.resources.limits.memory --
        memory: 128Mi
      #  deployment.kubeRbacProxy.resources.requests --
      requests:
        #  deployment.kubeRbacProxy.resources.requests.cpu --
        cpu: 5m
        #  deployment.kubeRbacProxy.resources.requests.memory --
        memory: 64Mi
    #  deployment.kubeRbacProxy.securityContext --
    securityContext:
      #  deployment.kubeRbacProxy.securityContext.allowPrivilegeEscalation --
      allowPrivilegeEscalation: false
      #  deployment.kubeRbacProxy.securityContext.capabilities --
      capabilities:
        #  deployment.kubeRbacProxy.securityContext.capabilities.drop --
        drop:
        - ALL
      #  deployment.kubeRbacProxy.securityContext.runAsNonRoot --
      runAsNonRoot: true
      #  deployment.kubeRbacProxy.securityContext.seccompProfile --
      seccompProfile:
        #  deployment.kubeRbacProxy.securityContext.seccompProfile.type --
        type: RuntimeDefault
  #  deployment.manager --
  manager:
    #  deployment.manager.args --
    args:
    - "--health-probe-bind-address=:8081"
    - "--metrics-bind-address=127.0.0.1:8080"
    - "--leader-elect"
    #  deployment.manager.command --
    command:
    - /manager
    #  deployment.manager.image --
    image:
      #  deployment.manager.image.repository --
      repository: ghcr.io/scc-digitalhub/dremio-rest-server-operator
      #  deployment.manager.image.tag --
      tag: ""
    #  deployment.manager.name --
    name: manager
    #  deployment.manager.resources --
    resources:
      #  deployment.manager.resources.limits --
      limits:
        #  deployment.manager.resources.limits.cpu --
        cpu: 500m
        #  deployment.manager.resources.limits.memory --
        memory: 128Mi
      #  deployment.manager.resources.requests --
      requests:
        #  deployment.manager.resources.requests.cpu --
        cpu: 10m
        #  deployment.manager.resources.requests.memory --
        memory: 64Mi
    #  deployment.manager.securityContext --
    securityContext:
      #  deployment.manager.securityContext.allowPrivilegeEscalation --
      allowPrivilegeEscalation: false
      #  deployment.manager.securityContext.capabilities --
      capabilities:
        #  deployment.manager.securityContext.capabilities.drop --
        drop:
        - ALL
      #  deployment.manager.securityContext.runAsNonRoot --
      runAsNonRoot: true
      #  deployment.manager.securityContext.seccompProfile --
      seccompProfile:
        #  deployment.manager.securityContext.seccompProfile.type --
        type: RuntimeDefault
#  fullnameOverride --
fullnameOverride: ""
#  imagePullSecrets --
imagePullSecrets: []
#  ingress --
ingress:
  #  ingress.annotations --
  annotations: {}
  #  ingress.className --
  className: ""
  #  ingress.enabled --
  enabled: false
  #  ingress.hosts --
  hosts:
  - host: chart-example.local
    paths:
    - path: /
      pathType: ImplementationSpecific
  #  ingress.tls --
  tls: []
#  nameOverride --
nameOverride: ""
#  namespaceValues --
namespaceValues:
  #  namespaceValues.namespace --
  namespace: ""
  #  namespaceValues.namespaced --
  namespaced: true
#  nodeSelector --
nodeSelector: {}
#  podAnnotations --
podAnnotations:
  #  podAnnotations.kubectl.kubernetes.io/default-container --
  kubectl.kubernetes.io/default-container: manager
#  podLabels --
podLabels:
  #  podLabels.control-plane --
  control-plane: controller-manager
#  podSecurityContext --
podSecurityContext:
  #  podSecurityContext.runAsNonRoot --
  runAsNonRoot: true
  #  podSecurityContext.seccompProfile --
  seccompProfile:
    #  podSecurityContext.seccompProfile.type --
    type: RuntimeDefault
#  replicaCount --
replicaCount: 1
#  resources --
resources: {}
#  service --
service:
  #  service.port --
  port: 8443
  #  service.type --
  type: ClusterIP
#  serviceAccount --
serviceAccount:
  #  serviceAccount.annotations --
  annotations: {}
  #  serviceAccount.automount --
  automount: true
  #  serviceAccount.create --
  create: true
  #  serviceAccount.name --
  name: dremio-rest-server-operator-controller-manager
#  tolerations --
tolerations: []
#  volumeMounts --
volumeMounts: []
#  volumes --
volumes: []
