{{ if .Values.namespaceValues.namespaced }}
{{- $roleCrd := (printf "%s-%s" (include "custom-resource-manager.fullname" .) "crd") -}}
{{- $roleCr := (printf "%s-%s" (include "custom-resource-manager.fullname" .) "cr") -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "custom-resource-manager.labels" . | nindent 4 }}
  name: {{ $roleCrd }}
rules:
- apiGroups:
  - "apiextensions.k8s.io"
  resources:
  - customresourcedefinitions
  verbs:
  - list
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $roleCr }}
rules:
{{- range .Values.crdAllowed }}
- apiGroups: [{{ .apiGroup }}]
  resources: [{{ join "," .resources }}]
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "custom-resource-manager.labels" . | nindent 4 }}
  name: {{ $roleCrd }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $roleCrd }}
subjects:
- kind: ServiceAccount
  name: {{ include "custom-resource-manager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "custom-resource-manager.labels" . | nindent 4 }}
  name: {{ $roleCr }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $roleCr }}
subjects:
- kind: ServiceAccount
  name: {{ include "custom-resource-manager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{ end }}