{{- if (index .Values "airflow" "enabled") }}
apiVersion: v1
data:
  password: {{ randAlphaNum 24 | nospace | b64enc }}
kind: Secret
metadata:
  name: airflow-admin-password
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
{{- end }}