# SPDX-FileCopyrightText: © 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: AGPL-3.0-or-later

{{ if not (and .Values.core.sts.enabled .Values.core.commonCredsSecret.useExistingCommonCredsSecret) -}}
{{- if ( index .Values "template-controller" "objectTemplate" "enabled" ) }}
apiVersion: templates.kluctl.io/v1alpha1
kind: ObjectTemplate
metadata:
  name: {{ include "digitalhub.fullname" . }}-common-creds-transformer
spec:
  serviceAccountName: secret-transformer
  prune: true
  matrix:
    - name: postgressecret
      object:
        ref:
          apiVersion: v1
          kind: Secret
          name: {{ .Values.core.databaseProvider.ownerSecret }}
    - name: s3secret
      object:
        ref:
          apiVersion: v1
          kind: Secret
          name: {{ .Values.global.s3.platform.platformUserSecret }}
    - name: coresecret
      object:
        ref:
          apiVersion: v1
          kind: Secret
          name: core-auth-creds
  templates:
  - object:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "digitalhub-common-creds"
      stringData:
        DB_USERNAME: "{{ "{{" }} matrix.postgressecret.data.username | b64decode {{ "}}" }}"
        DB_PASSWORD: "{{ "{{" }} matrix.postgressecret.data.password | b64decode {{ "}}" }}"
        AWS_ACCESS_KEY_ID: "{{ "{{" }} matrix.s3secret.data.accessKey | b64decode {{ "}}" }}"
        AWS_SECRET_ACCESS_KEY: "{{ "{{" }} matrix.s3secret.data.accessKey | b64decode {{ "}}" }}"
        DB_URL: "postgresql://{{ "{{" }} matrix.postgressecret.data.username | b64decode {{ "}}" }}:{{ "{{" }} matrix.postgressecret.data.password | b64decode {{ "}}" }}@{{ .Values.core.databaseProvider.host }}:{{ .Values.core.databaseProvider.port }}/{{ .Values.core.databaseProvider.database }}"
        DHCORE_CLIENT_ID: "{{ "{{" }} matrix.coresecret.data.clientId | b64decode {{ "}}" }}"
        {{- if .Values.core.authentication.basic.enabled }}
        DHCORE_USER: {{ .Values.core.authentication.basic.username }}
        DHCORE_PASSWORD: {{ .Values.core.authentication.basic.password }}
        {{- end }}
{{- end }}
{{- end }}
