{{- if not .Values.core.sts.enabled -}}
{{- if ( index .Values "template-controller" "objectTemplate" "enabled" ) }}
apiVersion: templates.kluctl.io/v1alpha1
kind: ObjectTemplate
metadata:
  name: {{ include "digitalhub.fullname" . }}-common-creds-transformer
spec:
  serviceAccountName: secret-transformer
  prune: true
  matrix:
    - name: postgressecret
      object:
        ref:
          apiVersion: v1
          kind: Secret
          name: digitalhub-owner-user.database-postgres-cluster.credentials.postgresql.acid.zalan.do
    - name: miniosecret
      object:
        ref:
          apiVersion: v1
          kind: Secret
          name: {{ .Values.global.minio.digitalhubUserSecret }}
    - name: coresecret
      object:
        ref:
          apiVersion: v1
          kind: Secret
          name: core-auth-creds
  templates:
  - object:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "digitalhub-common-creds"
      stringData:
        DHCORE_DB_USERNAME: "{{ "{{" }} matrix.postgressecret.data.username | b64decode {{ "}}" }}"
        DHCORE_DB_PASSWORD: "{{ "{{" }} matrix.postgressecret.data.password | b64decode {{ "}}" }}"
        DHCORE_AWS_ACCESS_KEY_ID: "{{ "{{" }} matrix.miniosecret.data.digitalhubUser | b64decode {{ "}}" }}"
        DHCORE_AWS_SECRET_ACCESS_KEY: "{{ "{{" }} matrix.miniosecret.data.digitalhubPassword | b64decode {{ "}}" }}"
        DHCORE_DB_URL: "postgresql://{{ "{{" }} matrix.postgressecret.data.username | b64decode {{ "}}" }}:{{ "{{" }} matrix.postgressecret.data.password | b64decode {{ "}}" }}@database-postgres-cluster:5432/digitalhub"
        DHCORE_JWT_CLIENT_ID: "{{ "{{" }} matrix.coresecret.data.clientId | b64decode {{ "}}" }}"
{{- end }}
{{- end }}
