apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: database-postgres-cluster
spec:
  teamId: "digitalhub"
  volume:
    size: {{ index .Values "postgres-operator" "digitalhubDatabase" "volume" "size" }}
  numberOfInstances: 3
  users:
    digitalhubadmin:
    - superuser
    - createdb
  postgresql:
    version: "15"
  preparedDatabases:
    digitalhub:
      defaultUsers: true
      schemas:
        public:
          defaultUsers: true
  resources:
  {{- toYaml ( index .Values "postgres-operator" "digitalhubDatabase" "resources" ) | nindent 4 }}