apiVersion: templates.kluctl.io/v1alpha1
kind: ObjectTemplate
metadata:
  name: minio-aac-secret-transformer
spec:
  serviceAccountName: secret-transformer
  prune: false
  matrix:
    - name: aacminiosecret
      object:
        ref:
          apiVersion: v1
          kind: Secret
          name: aac-digitalhub-minio-secret
  templates:
  - object:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "minio-auth-secret"
      stringData:
        config.env: |-
          MINIO_IDENTITY_OPENID_CLIENT_ID="{{ "{{" }} matrix.aacminiosecret.data.clientid | b64decode {{ "}}" }}"
          MINIO_IDENTITY_OPENID_CLIENT_SECRET="{{ "{{" }} matrix.aacminiosecret.data.clientsecret | b64decode {{ "}}" }}"
