{{- if and .Values.openmetadata.enabled .Values.openmetadata.initializer.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openmetadata-initializer
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation,hook-failed
    "helm.sh/hook-weight": "1"
  labels:
    {{- include "digitalhub.labels" . | nindent 4 }}
---
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openmetadata-initializer
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation,hook-failed
    "helm.sh/hook-weight": "1"
  labels:
    {{- include "digitalhub.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openmetadata-initializer
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation,hook-failed
    "helm.sh/hook-weight": "1"
  labels:
    {{- include "digitalhub.labels" .  | nindent 4}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openmetadata-initializer
subjects:
  - name: openmetadata-initializer
    namespace: {{ .Release.Namespace }}
    kind: ServiceAccount
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openmetadata-initializer
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation,hook-failed
    "helm.sh/hook-weight": "1"
  labels:
    {{- include "digitalhub.labels" . | nindent 4 }}
data:
    USERNAME: {{ .Values.openmetadata.initializer.username }}
    PASSWORD: {{ .Values.openmetadata.initializer.password }}
    HOSTNAME: "http://{{ include "OpenMetadata.fullname" .Subcharts.openmetadata }}"
    PORT: "8585"
    ADMIN_PORT: "8586"
    GENERATE_TOKEN: "true"
    CHANGE_USER_PASSWORD: "false"
    READINESS_MAX_RETRY: {{ .Values.openmetadata.initializer.maxRetry | quote }}
    NAMESPACE: {{ .Release.Namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: openmetadata-initializer
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "3"
  labels:
    {{- include "digitalhub.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      name: openmetada-initializer
      labels:
        {{- include "digitalhub.labels" . | nindent 8 }}
    spec:
      serviceAccountName: openmetadata-initializer
      containers:
        - name: openmetadata-initializer
          image: "ghcr.io/scc-digitalhub/openmetadata-initilizer:1.0.0"
          securityContext:
            {{- toYaml .Values.global.securityContext | nindent 12}}
            readOnlyRootFilesystem: {{ .Values.jobs.delete.securityContext.readOnlyRootFilesystem }}
          envFrom:
            - configMapRef:
                name: openmetadata-initializer
      restartPolicy: OnFailure
      backoffLimit: 20
{{- end }}