{{- if (index .Values "rabbitmq-cluster-operator" "enabled") }}
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: digitalhub-rabbitmq
spec:
  replicas: {{ index .Values "rabbitmq-cluster-operator" "cluster" "replicas" }}
  resources:
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      cpu: 2
      memory: 2Gi
  rabbitmq:
    additionalConfig: |
      vm_memory_high_watermark_paging_ratio = 0.99
      disk_free_limit.relative = 1.0
      collect_statistics_interval = 10000
  persistence:
    storageClassName: {{ index .Values "rabbitmq-cluster-operator" "cluster" "persistence" "storageClass" }}
    storage: {{ index .Values "rabbitmq-cluster-operator" "cluster" "persistence" "storageSize" }}
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - digitalhub-rabbitmq
        topologyKey: kubernetes.io/hostname
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers: []
            topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: "kubernetes.io/hostname"
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: digitalhub-rabbitmq
{{- end }}