# SPDX-FileCopyrightText: © 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: AGPL-3.0-or-later

{{ if and .Values.global.ociRegistry.username .Values.global.ociRegistry.password .Values.global.ociRegistry.email -}}
apiVersion: v1
data:
  .dockerconfigjson: {{ tpl (.Files.Get "confs/.dockerconfigjson") . | b64enc }}
kind: Secret
metadata:
  name: {{ .Values.global.ociRegistry.secretName }}
type: kubernetes.io/dockerconfigjson
{{- end }}
