# SPDX-FileCopyrightText: © 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: AGPL-3.0-or-later

{{ if .Values.seaweedfs.enabled -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.seaweedfs.s3.existingConfigSecret }}
stringData:
  # this key must be an inline json config file
  seaweedfs_s3_config: '{"identities":[{"name":"{{ .Values.global.s3.rootUser }}","credentials":[{"accessKey":"{{ .Values.global.s3.rootUser }}","secretKey":"{{ .Values.global.s3.rootPassword }}"}],"actions":["Admin","Read","Write"]},{"name":"{{ .Values.global.s3.platform.accessKey }}","credentials":[{"accessKey":"{{ .Values.global.s3.platform.accessKey }}","secretKey":"{{ .Values.global.s3.platform.secretKey }}"}],"actions":["Read:{{ .Values.global.s3.platform.bucket }}","Write:{{ .Values.global.s3.platform.bucket }}"]},{"name":"{{ .Values.global.s3.argo.accessKey }}","credentials":[{"accessKey":"{{ .Values.global.s3.argo.accessKey }}","secretKey":"{{ .Values.global.s3.argo.secretKey }}"}],"actions":["Read:{{ .Values.global.s3.argo.bucket }}","Write:{{ .Values.global.s3.argo.bucket}}"]}]}'
{{- end }}
