apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "core.fullname" . }}
data:
  DHUB_CORE_ENDPOINT: "{{ include "core.fullname" . }}:{{ .Values.service.port }}"
  S3_ENDPOINT_URL: "{{ .Values.minio.endpoint }}:{{ index .Values.minio.endpointPort }}"
  S3_BUCKET_NAME: core
  POSTGRES_HOST: "core-postgres-cluster:5432"
  POSTGRES_PORT: "5432"
  POSTGRES_DATABASE: dbt
  POSTGRES_SCHEMA: public