apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "core.fullname" . }}
data:
  DH_ENDPOINT: "http://{{ include "core.fullname" . }}:{{ .Values.service.port }}"
  DH_S3_ENDPOINT_URL: "{{ .Values.minio.endpoint }}:{{ index .Values.minio.endpointPort }}"
  DH_S3_BUCKET_NAME: core
  DH_POSTGRES_HOST: "database-postgres-cluster"
  DH_POSTGRES_PORT: "5432"
  DH_POSTGRES_DATABASE: database
  DH_POSTGRES_SCHEMA: public
  K8S_NAMESPACE: {{ .Release.Namespace }}
  JDBC_URL: "jdbc:postgresql://core-postgres-cluster:5432/core"
  JDBC_DRIVER: org.postgresql.Driver
  JDBC_DIALECT: org.hibernate.dialect.PostgreSQLDialect
  H2_CONSOLE: "false"