apiVersion: v1
kind: Service
metadata:
  labels:
    app: ml-pipeline-ui
    application-crd-id: kubeflow-pipelines
  name: ml-pipeline-ui
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
    nodePort: {{ .Values.ui.service.nodePort }}
  selector:
    app: ml-pipeline-ui
    application-crd-id: kubeflow-pipelines
  type: {{ .Values.ui.service.type }}
