apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
 name: defaultstorageclass
spec:
 strategy: "ApplyOnce"
 clusterSelector:
   matchLabels:
     cloud-provider: azure
 resources:
   - name: default-storageclass
     kind: ConfigMap