apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ml-pipeline-ui
    application-crd-id: kubeflow-pipelines
  name: ml-pipeline-ui
spec:
  selector:
    matchLabels:
      app: ml-pipeline-ui
      application-crd-id: kubeflow-pipelines
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        checksum/config: {{ include (print $.Template.BasePath "/configmaps/ml-pipeline-ui-configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets/mlpipeline-s3-artifact.yaml") . | sha256sum }}
      labels:
        app: ml-pipeline-ui
        application-crd-id: kubeflow-pipelines
    spec:
      containers:
      - env:
        - name: VIEWER_TENSORBOARD_POD_TEMPLATE_SPEC_PATH
          value: /etc/config/viewer-pod-template.json
        - name: MINIO_HOST
          value: {{ include "kubeflow-pipelines.s3-pipeline.service.url" . }}
        - name: MINIO_PORT
          value: "{{ .Values.s3.endpointPort }}"
        - name: MINIO_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
            {{- if .Values.s3.externalSecret.secretName }}
              key: {{ .Values.s3.externalSecret.accessKeyField }}
              name: {{ .Values.s3.externalSecret.secretName }}
            {{- else }}
              key: accesskey
              name: mlpipeline-s3-artifact
            {{- end }}
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
            {{- if .Values.s3.externalSecret.secretName }}
              key: {{ .Values.s3.externalSecret.secretKeyField }}
              name: {{ .Values.s3.externalSecret.secretName }}
            {{- else }}
              key: secretkey
              name: mlpipeline-s3-artifact
            {{- end }}
        - name: ALLOW_CUSTOM_VISUALIZATIONS
          value: "true"
        - name: DISABLE_GKE_METADATA
          value: "true"
        - name: FRONTEND_SERVER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: {{ .Values.images.ui.repository }}:{{ .Values.images.ui.tag }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - wget
            - -q
            - -S
            - -O
            - '-'
            - http://localhost:3000/apis/v1beta1/healthz
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 2
        name: ml-pipeline-ui
        ports:
        - containerPort: 3000
        readinessProbe:
          exec:
            command:
            - wget
            - -q
            - -S
            - -O
            - '-'
            - http://localhost:3000/apis/v1beta1/healthz
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 2
        resources:
          requests:
            cpu: 10m
            memory: 70Mi
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
          readOnly: true
      serviceAccountName: ml-pipeline-ui
      volumes:
      - configMap:
          name: ml-pipeline-ui-configmap
        name: config-volume
      {{- with .Values.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
