{{- if .Values.pipelines.ui.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ml-pipeline-ui
  labels:
    app: ml-pipeline-ui
    application-crd-id: kubeflow-pipelines
  {{- with .Values.pipelines.ui.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.pipelines.ui.ingress.ingressClassName }}
  ingressClassName: {{ .Values.pipelines.ui.ingress.ingressClassName }}
{{- end }}
{{- if .Values.pipelines.ui.ingress.tls }}
  tls:
  {{- range .Values.pipelines.ui.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.pipelines.ui.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - pathType: {{ .pathType }}
            path: {{ .path }}
            backend:
              service:
                name: ml-pipeline-ui
                port: 
                  number: 80
          {{- end }}
  {{- end }}
{{- end }}
