services:
  #service for Dagster Postgres storage DB
  dagster_postgresql:
    image: postgres:11
    container_name: dagster_postgresql
    expose:
      - "5433"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "dagster_storage"
      PGPORT: 5433

  dagit:
    image: ghcr.io/scc-digitalhub/dagster:0.1.0
    entrypoint:
      - dagit
      - -h
      - "0.0.0.0"
      - -p
      - "5000"
      - -w
      - workspace.yaml
    expose:
      - "5000"
    ports:
      - "5000:5000"
    environment:
      # backend storage
      DAGSTER_POSTGRES_USER: "postgres"
      DAGSTER_POSTGRES_PASSWORD: "postgres"
      DAGSTER_POSTGRES_DB: "dagster_storage"
      DAGSTER_POSTGRES_PORT: 5433
      # credentials for the pipeline
      DH_DB_USERNAME: "postgres"
      DH_DB_PWD: "postgres"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECREY_KEY: "minioadmin"
    volumes:
      - ./resources/dagster-pipelines:/opt/dagster/code
    depends_on:
      - dagster_postgresql

  dagster_daemon:
    image: ghcr.io/scc-digitalhub/dagster:0.1.0
    entrypoint:
      - dagster-daemon
      - run
    restart: on-failure
    environment:
      # backend storage
      DAGSTER_POSTGRES_USER: "postgres"
      DAGSTER_POSTGRES_PASSWORD: "postgres"
      DAGSTER_POSTGRES_DB: "dagster_storage"
      DAGSTER_POSTGRES_PORT: 5433
      # credentials for the pipeline
      DH_DB_USERNAME: "postgres"
      DH_DB_PWD: "postgres"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECREY_KEY: "minioadmin"
    volumes:
      - ./resources/dagster-pipelines:/opt/dagster/code
    depends_on:
      - dagster_postgresql
