services:
  # Postgres service with TimescaleDB, PostGIS and GraphQL
  postgres:
    image: ghcr.io/scc-digitalhub/postgres-graphql:0.1.0
    volumes:
        - ./resources/db-init-scripts/postgres-expose-virtualize.sql:/docker-entrypoint-initdb.d/postgres.sql
    ports:
      - 5432:5432
    command:
      - postgres
      - -c
      - wal_level=logical
      - -c
      - shared_preload_libraries=pg_stat_statements,timescaledb
      - -c
      - timescaledb.telemetry_level=off
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: digitalhub

  # PostgREST service
  postgrest:
    image: postgrest/postgrest:v10.0.0
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@postgres:5432/digitalhub
      PGRST_DB_SCHEMA: test_scenario, graphql, public
      PGRST_JWT_SECRET: '{
        "keys": [
          {
            "kty": "RSA",
            "e": "AQAB",
            "use": "sig",
            "kid": "rsa1",
            "alg": "RS256",
            "n": "n_claim_from_aac_jwk_endpoint"
          }
        ]
      }'
      # PGRST_DB_ANON_ROLE: test_scenario_user # Comment to disable anonymous access

  # GraphiQL service
  graphiql:
    image: nginx
    volumes:
      - ./resources/index.html:/usr/share/nginx/html/index.html
    ports:
      - 4000:80
    depends_on:
      - postgrest

  # MinIO service
  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data/minio:/data
    environment:
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
    command: server /data --console-address ":9001"

  # Dremio service
  #TODO

  # Micro Integrator service
  wso2mi:
    image: wso2/wso2mi:4.1.0-multiarch
    ports:
      - 8253:8253
      - 8290:8290
      - 9164:9164
    volumes:
      - "./resources/postgresql-42.5.0.jar:/home/wso2carbon/wso2mi-4.1.0/lib/postgresql-42.5.0.jar"
      - "./resources/PostgresIntegration_1.0.0.car:/home/wso2carbon/wso2mi-4.1.0/repository/deployment/server/carbonapps/PostgresIntegration_1.0.0.car"

# Default network with static subnet
networks:
  default:
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1