services:
  postgres:
    image: ghcr.io/scc-digitalhub/postgres-graphql:0.1.0
    volumes:
        - ./resources/db-init-scripts/postgres-virtualization.sql:/docker-entrypoint-initdb.d/postgres.sql
    ports:
      - 5432:5432
    command:
      - postgres
      - -c
      - wal_level=logical
      - -c
      - shared_preload_libraries=pg_stat_statements,timescaledb
      - -c
      - timescaledb.telemetry_level=off
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: digitalhub

  postgrest:
    image: postgrest/postgrest:v10.0.0
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:192.168.123.123"
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@host.docker.internal:5432/digitalhub
      PGRST_DB_SCHEMA: test_scenario, graphql, public
      PGRST_JWT_SECRET: '12345678901234567890123456789012'
      PGRST_DB_ANON_ROLE: test_scenario_user # Comment to disable anonymous access

  graphiql:
    image: nginx
    volumes:
      - ./resources/index.html:/usr/share/nginx/html/index.html
    ports:
      - 4000:80
    depends_on:
      - postgrest