services:
  nifi:
    image: ghcr.io/scc-digitalhub/nifi-oidc:0.1.0
    ports:
      - 8443:8443
    extra_hosts:
      - "host.docker.internal:192.168.123.123"
    volumes:
      - "./resources/postgresql-42.5.0.jar:/opt/nifi/nifi-current/lib/postgresql-42.5.0.jar"
      - "./resources/certs:/opt/nifi/nifi-current/conf/certs"
    environment:
      SINGLE_USER_CREDENTIALS_USERNAME: 'admin' # For use when OIDC is disabled. Ignored if OIDC is enabled.
      SINGLE_USER_CREDENTIALS_PASSWORD: 'admin1234567' # For use when OIDC is disabled. Ignored if OIDC is enabled.
      #AUTH: 'oidc' # Uncomment to enable OpenID Connect authentication.
      OIDC_CONFIGURATION: 'https://<aac_instance>/.well-known/openid-configuration'
      NIFI_CLIENT_ID: '<aac_client_id>'
      NIFI_CLIENT_SECRET: '<aac_client_secret>'
      KEYSTORE_PATH: './conf/certs/keystore.jks'
      KEYSTORE_TYPE: 'jks'
      KEYSTORE_PASSWORD: 'platform'
      KEY_PASSWORD: 'platform'
      TRUSTSTORE_PATH: './conf/certs/truststore.jks'
      TRUSTSTORE_TYPE: 'jks'
      TRUSTSTORE_PASSWORD: 'platform'
      INITIAL_ADMIN_IDENTITY: '<your@aac.account>'
      