services:
  # Postgres service with TimescaleDB and PostGIS
  postgres:
    image: timescale/timescaledb-ha:pg14.6-ts2.8.1-latest
    volumes:
        - ./resources/db-init-scripts/postgres-protected-components.sql:/docker-entrypoint-initdb.d/postgres.sql
        - ./resources/db-init-scripts/hdb_catalog.sql:/docker-entrypoint-initdb.d/hdb_catalog.sql
    ports:
      - "5432:5432"
    command:
      - postgres
      - -c
      - timescaledb.telemetry_level=off
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"

  # PostgREST service
  postgrest:
    image: postgrest/postgrest:v10.0.0
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      PGRST_DB_URI: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
      PGRST_DB_SCHEMA: test_scenario, graphql, public
      PGRST_JWT_SECRET: '{
        "keys": [
          {
            "kty": "RSA",
            "e": "AQAB",
            "use": "sig",
            "kid": "rsa1",
            "alg": "RS256",
            "n": "${AAC_JWK_MODULUS_N_CLAIM}"
          }
        ]
      }'

  # MinIO service
  minio:
    image: minio/minio:RELEASE.2022-11-26T22-43-32Z.fips
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
      MINIO_IDENTITY_OPENID_CONFIG_URL: "${AAC_INSTANCE}/.well-known/openid-configuration"
      MINIO_IDENTITY_OPENID_CLIENT_ID: "${MINIO_CLIENT_ID}"
      MINIO_IDENTITY_OPENID_CLIENT_SECRET: "${MINIO_CLIENT_SECRET}"
      MINIO_IDENTITY_OPENID_CLAIM_NAME: policy
      MINIO_IDENTITY_OPENID_SCOPES: openid
      MINIO_IDENTITY_OPENID_REDIRECT_URI: http://localhost:9001/oauth_callback
      MINIO_IDENTITY_OPENID_CLAIM_USERINFO: "on"
    command: server /data --console-address ":9001"

  # NiFi service
  nifi:
    image: ghcr.io/scc-digitalhub/nifi-oidc:0.1.1
    ports:
      - "8443:8443"
    volumes:
      - ./resources/postgresql-42.5.0.jar:/opt/nifi/nifi-current/lib/postgresql-42.5.0.jar
      - ./resources/certs:/opt/nifi/nifi-current/conf/certs
    environment:
      AUTH: oidc
      OIDC_CONFIGURATION: "${AAC_INSTANCE}/.well-known/openid-configuration"
      NIFI_CLIENT_ID: "${NIFI_CLIENT_ID}"
      NIFI_CLIENT_SECRET: "${NIFI_CLIENT_SECRET}"
      KEYSTORE_PATH: ./conf/certs/keystore.jks
      KEYSTORE_TYPE: jks
      KEYSTORE_PASSWORD: platform
      KEY_PASSWORD: platform
      TRUSTSTORE_PATH: ./conf/certs/truststore.jks
      TRUSTSTORE_TYPE: jks
      TRUSTSTORE_PASSWORD: platform
      INITIAL_ADMIN_IDENTITY: "${NIFI_INITIAL_ADMIN_IDENTITY}"

  # Dremio service
  #
  #
  #TODO
  #
  #

  # SQLPad service
  sqlpad:
    image: sqlpad/sqlpad:6.11.2 #last stable multiplatform version
    ports:
      - "4000:4000"
    environment:
      SQLPAD_PORT: 4000
      SQLPAD_ADMIN: "${SQLPAD_ADMIN}"
      SQLPAD_ADMIN_PASSWORD: "${SQLPAD_ADMIN_PASSWORD}"
      # Predefined connection to Postgres
      SQLPAD_CONNECTIONS__postgres1__name: Digitalhub
      SQLPAD_CONNECTIONS__postgres1__driver: postgres
      SQLPAD_CONNECTIONS__postgres1__host: postgres
      SQLPAD_CONNECTIONS__postgres1__port: 5432
      SQLPAD_CONNECTIONS__postgres1__database: "${POSTGRES_DB}"
      SQLPAD_CONNECTIONS__postgres1__username: "${POSTGRES_USER}"
      SQLPAD_CONNECTIONS__postgres1__password: "${POSTGRES_PASSWORD}"
      # OIDC configuration (OIDC users are assigned "editor" role)
      PUBLIC_URL: http://localhost:4000
      SQLPAD_OIDC_LINK_HTML: 'Sign in with AAC'
      SQLPAD_OIDC_CLIENT_ID: "${SQLPAD_OIDC_CLIENT_ID}"
      SQLPAD_OIDC_CLIENT_SECRET: "${SQLPAD_OIDC_CLIENT_SECRET}"
      SQLPAD_OIDC_SCOPE: 'openid profile email'
      SQLPAD_OIDC_ISSUER: "${SQLPAD_OIDC_ISSUER}"
      SQLPAD_OIDC_AUTHORIZATION_URL: "${SQLPAD_OIDC_ISSUER}/oauth/authorize"
      SQLPAD_OIDC_TOKEN_URL: "${SQLPAD_OIDC_ISSUER}/oauth/token"
      SQLPAD_OIDC_USER_INFO_URL: "${SQLPAD_OIDC_ISSUER}/userinfo"

      SQLPAD_ALLOWED_DOMAINS: "${SQLPAD_ALLOWED_DOMAINS}" #space delimited list of email domains to auto-add users after login
      SQLPAD_USERPASS_AUTH_DISABLED: 'true'
      SQLPAD_SESSION_COOKIE_SAME_SITE: Lax

  # Dagster services (Dagit and Daemon)
  # NOTE: these services are currently not protected
  dagit:
    image: ghcr.io/scc-digitalhub/dagster:0.1.0
    entrypoint:
      - dagit
      - -h
      - "0.0.0.0"
      - -p
      - "5000"
      - -w
      - workspace.yaml
    ports:
      - "5000:5000"
    environment:
      # backend storage
      DAGSTER_POSTGRES_USER: "${POSTGRES_USER}"
      DAGSTER_POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      DAGSTER_POSTGRES_DB: dagster_storage
      DAGSTER_POSTGRES_PORT: 5432
      # credentials for the pipeline
      DH_DB_USERNAME: "${POSTGRES_USER}"
      DH_DB_PWD: "${POSTGRES_PASSWORD}"
      MINIO_ACCESS_KEY: "${MINIO_ROOT_USER}"
      MINIO_SECREY_KEY: "${MINIO_ROOT_PASSWORD}"
    volumes:
      - ./resources/dagster-pipelines:/opt/dagster/code
    depends_on:
      - postgres

  dagster_daemon:
    image: ghcr.io/scc-digitalhub/dagster:0.1.0
    entrypoint:
      - dagster-daemon
      - run
    restart: on-failure
    environment:
      # backend storage
      DAGSTER_POSTGRES_USER: "${POSTGRES_USER}"
      DAGSTER_POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      DAGSTER_POSTGRES_DB: dagster_storage
      DAGSTER_POSTGRES_PORT: 5432
      # credentials for the pipeline
      DH_DB_USERNAME: "${POSTGRES_USER}"
      DH_DB_PWD: "${POSTGRES_PASSWORD}"
      MINIO_ACCESS_KEY: "${MINIO_ROOT_USER}"
      MINIO_SECREY_KEY: "${MINIO_ROOT_PASSWORD}"
    volumes:
      - ./resources/dagster-pipelines:/opt/dagster/code
    depends_on:
      - postgres

  # Hasura services (Hasura itself, OAuth2-proxy, Redis and Nginx)
  hasura:
    image: hasura/graphql-engine:v2.10.2.ubuntu
    restart: on-failure
    ports:
      - "3100:8080"
    depends_on:
      - postgres
    environment:
      HASURA_GRAPHQL_DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'false'
      HASURA_GRAPHQL_ENABLE_TELEMETRY: 'false'
      HASURA_GRAPHQL_JWT_SECRET: '{
       "jwk_url": "${AAC_INSTANCE}/jwk",
       "issuer": "${AAC_INSTANCE}",
       "audience": "${HASURA_AUDIENCE}"
      }'
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET}"

# Default network with static subnet
networks:
  default:
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
