services:
  wso2mi:
    image: wso2/wso2mi:4.1.0-multiarch
    ports:
      - 8253:8253
      - 8290:8290
      - 9164:9164
    volumes:
      - "./resources/some_integration_service.car:/home/wso2carbon/wso2mi-4.1.0/repository/deployment/server/carbonapps/some_integration_service.car"
      - "./resources/postgresql-42.5.0.jar:/home/wso2carbon/wso2mi-4.1.0/lib/postgresql-42.5.0.jar"