# SPDX-FileCopyrightText: © 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aac.fullname" . }}
data:
  JDBC_DIALECT: {{ .Values.config.jdbcDialect }}
  JDBC_DRIVER: {{ .Values.config.jdbcDriver }}
  JDBC_URL: {{ .Values.config.jdbcUrl }}
  MAIL_HOST: {{ .Values.config.mailHost }}
  MAIL_PORT: {{ .Values.config.mailPort | quote }}
  MAIL_PROTOCOL: {{ .Values.config.mailProtocol }}
  MAIL_TLS: {{ .Values.config.mailTls | quote }}
  MAIL_SENDER: {{ .Values.config.mailSender }}
  MAIL_DEBUG: {{ .Values.config.mailDebug | quote }}
  BOOTSTRAP_APPLY: {{ .Values.config.bootstrapApply | quote }}
  BOOTSTRAP: {{ .Values.config.bootstrap }}
  LOG_LEVEL: {{ .Values.config.logLevel }}
  APPLICATION_EXT_URL: {{ .Values.config.applicationExtUrl }}
  APPLICATION_EMAIL: {{ .Values.config.mailSender }}
  {{ if and .Values.keystore.secretName .Values.config.keystorePath -}}
  JWK_KEYSTORE: "file://{{ .Values.config.keystorePath }}/{{ .Values.keystore.keyName }}"
  SECURITY_CACHE_JWKS: {{ .Values.config.cacheJwks }}
  {{ end -}}
