apiVersion: v1
kind: Service
metadata:
  name: {{ include "aac.fullname" . }}
  labels:
    {{- include "aac.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{ if eq .Values.service.type "NodePort" }}nodePort: {{ .Values.service.httpNodePort }}{{ end }}
  selector:
    {{- include "aac.selectorLabels" . | nindent 4 }}
