apiVersion: v2
name: apigw-operator
description: A Helm chart for Kubernetes
type: application
version: 0.1.3
appVersion: "1.0.5"
maintainers:
  - name: ffais
    url: https://github.com/ffais
  - name: calcagiara
    url: https://github.com/Calcagiara