apiVersion: v2
name: apigw-operator
description: A Helm chart for Kubernetes
home: "https://github.com/scc-digitalhub/digitalhub/tree/main/charts/apigw-operator"
type: application
version: 0.1.9
appVersion: "1.1.2"
maintainers:
  - name: ffais
    url: https://github.com/ffais
  - name: calcagiara
    url: https://github.com/Calcagiara
