# Workspace configuration, see https://docs.dagster.io/concepts/repositories-workspaces/workspaces
load_from:
  # local or installed package, e.g.:
  # - python_package: hello_world_package

  # code or repository definition, e.g.:
  # - python_file: repository.py

  # gRPC server, e.g.:
  # - grpc_server:
  #     host: localhost
  #     port: 4266
  #     location_name: "my_grpc_server"
  - python_file: csv_pipeline.py