# SPDX-FileCopyrightText: © 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: postgrest-operator
description: A Helm chart for Kubernetes
home: "https://github.com/scc-digitalhub/digitalhub/tree/main/charts/postgrest-operator"
type: application
version: 0.1.8
appVersion: "2.0.5"
maintainers:
  - name: ffais
    url: https://github.com/ffais
  - name: calcagiara
    url: https://github.com/Calcagiara
