{{ if .Values.rbac.roles.namespaced }}
{{- $roleCrd := (printf "%s-%s" (include "custom-resource-manager.fullname" .) "crd") -}}
{{- $roleCr := (printf "%s-%s" (include "custom-resource-manager.fullname" .) "cr") -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $roleCr }}
rules:
{{- range .Values.rbac.roles }}
- apiGroups: {{ if .apiGroups }}[{{ .apiGroups }}]{{ else }}[""]{{ end }}
  resources: {{ list (.resources) }}
  verbs: {{ list (.verbs) }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "custom-resource-manager.labels" . | nindent 4 }}
  name: {{ $roleCr }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $roleCr }}
subjects:
- kind: ServiceAccount
  name: {{ include "custom-resource-manager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{ end }}