apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubernetes-resource-manager.fullname" . }}
data:
  K8S_SELECTOR_SERVICE: "app.kubernetes.io/part-of=coder,app.kubernetes.io/type=service|nuclio.io/class=function|app.kubernetes.io/managed-by=postgrest-operator|app.kubernetes.io/managed-by=dremiorestserver-operator|com.coder.resource=true"
  K8S_SELECTOR_DEPLOYMENT: "app.kubernetes.io/type=workspace,app.kubernetes.io/managed-by=dhcore"
  K8S_SELECTOR_JOB: "app.kubernetes.io/managed-by=dhcore"
  K8S_SELECTOR_PVC: "app.kubernetes.io/managed-by=krm"
  K8S_PVC_MANAGED_BY: krm
  K8S_PVC_STORAGE_CLASSES: {{ .Values.storageClasses }}
  K8S_NAMESPACE: {{ include "kubernetes-resource-manager.namespaceCheck" . | quote }}
  K8S_CRD_ALLOWED: {{ include "kubernetes-resource-manager.allowedCrd" . }}
  APPLICATION_URL: {{ include "kubernetes-resource-manager.defaultAccessURL" . }}
  K8S_SELECTOR_OWNERS: "db.movetokube.com/v1alpha1"
  K8S_SELECTOR_LABELS: ""
  K8S_SELECTOR_NAMES: "(digitalhub\\-owner|digitalhub\\-reader|digitalhub\\-writer).*"
  KRM_AUTH_OAUTH2_ISSUER: {{ .Values.oidc.issuer }}
  SCOPE: {{ .Values.oidc.scope }}
  AUTH_TYPE: {{ .Values.oidc.authType }}
  REDIRECT_URL: {{ .Values.oidc.redirectUrl }}
