# SPDX-FileCopyrightText: © 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: AGPL-3.0-or-later

{{ if .Values.coder.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: dremio-init-data
data:
{{ (.Files.Glob "confs/dremio/add_source_with_api.sh").AsConfig | indent 2 }}
{{ (.Files.Glob "confs/dremio/init-data.sh").AsConfig | indent 2 }}
{{- end }}
