{{- if not .Values.s3.externalSecret.secretName }}
apiVersion: v1
data:
  accesskey: {{ .Values.s3.accessKey | b64enc | quote }}
  secretkey: {{ .Values.s3.secretKey | b64enc | quote }}
kind: Secret
metadata:
  annotations:
  labels:
    application-crd-id: kubeflow-pipelines
  name: mlpipeline-s3-artifact
type: Opaque
{{- end }}
