{{- if not .Values.db.externalSecret.secretName }}
apiVersion: v1
data:
  password: {{ .Values.embeddedMySql.rootPassword | b64enc | quote }}
  username: {{ .Values.embeddedMySql.rootUsername | b64enc | quote }}
kind: Secret
metadata:
  annotations:
  labels:
    application-crd-id: kubeflow-pipelines
  name: mysql-root-secret
type: Opaque
---
apiVersion: v1
data:
  password: {{ .Values.db.password | b64enc | quote }}
  username: {{ .Values.db.username | b64enc | quote }}
kind: Secret
metadata:
  annotations:
  labels:
    application-crd-id: kubeflow-pipelines
  name: mysql-secret
type: Opaque
---
{{- $init := tpl (.Files.Get "confs/init.sql") . }}
apiVersion: v1
data:
  init.sql: {{ $init | b64enc }}
kind: Secret
metadata:
  annotations:
  labels:
    application-crd-id: kubeflow-pipelines
  name: mysql-init-config
type: Opaque
{{- end }}
