{{- if .Values.coder.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: coder-postgresql-creds
  annotations:
    "helm.sh/hook": post-install, post-upgrade
type: Opaque
data:
{{- $secret := (lookup "v1" "Secret" .Release.Namespace .Values.coder.postgres.coderUserSecret ) -}}
{{- if $secret -}}
{{- $username := (index $secret.data "username") | b64dec }}
{{- $password := (index $secret.data "password") | b64dec }}
  uri: {{ printf "postgres://%s:%s@%s:%s/%s" $username $password .Values.coder.postgres.host .Values.coder.postgres.port .Values.coder.postgres.database | b64enc }}
{{- end -}}
{{- end }}
