{{- if .Values.coder.enabled }}
{{- range .Values.coder.template.customTemplates }}
{{- if .extraVars  }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}-additional-env
data:
{{- range .extraVars }}
  {{ .name }}: {{ .value | quote }}
{{- end }}
---
{{- end }}
{{- end }}
{{- end }}
