apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openmetadata-java-connector.fullname" . }}
  labels:
    {{- include "openmetadata-java-connector.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "openmetadata-java-connector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "openmetadata-java-connector.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openmetadata-java-connector.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if or (not .Values.connector.rabbitmq.existingSecrets.username.secretName) (not .Values.connector.rabbitmq.existingSecrets.password.secretName) (not .Values.connector.openmetadata.existingSecrets.token.secretName) }}
          envFrom:
            - secretRef:
                name: {{ include "openmetadata-java-connector.fullname" . }}            
          {{- else }}
          env:
            {{- if and (not .Values.connector.rabbitmq.password) (.Values.connector.rabbitmq.existingSecrets.password.secretName) }}
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.connector.rabbitmq.existingSecrets.password.secretName }}
                  key: {{ .Values.connector.rabbitmq.existingSecrets.password.secretKey }}
            {{- end }}
            {{- if and (not .Values.connector.rabbitmq.username) (.Values.connector.rabbitmq.existingSecrets.username.secretName) }}
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.connector.rabbitmq.existingSecrets.username.secretName }}
                  key: {{ .Values.connector.rabbitmq.existingSecrets.username.secretKey }}
            {{- end }}
            {{- if and (not .Values.connector.openmetadata.token) (.Values.connector.openmetadata.existingSecrets.token.secretName) }}
            - name: OPENMETADATA_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.connector.openmetadata.existingSecrets.token.secretName }}
                  key: {{ .Values.connector.openmetadata.existingSecrets.token.secretKey }}
            {{- end }}
          {{- end }}
          envFrom:
          - configMapRef:
              name: {{ .Chart.Name }}-configmap
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
