site_name: Digital Hub

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - 'index.md'
  - 'architecture.md'
  - 'installation.md'
  - 'core.md'
  - Components:
    - 'components/deploying-components.md'
    - 'components/dashboard.md'
    - 'components/jupyter.md'
    - 'components/dremio.md'
    - 'components/mlrun.md'
    - 'components/sqlpad.md'
    - 'components/grafana.md'
    - 'components/vscode.md'
  - Tasks:
    - 'tasks/projects.md'
    - 'tasks/workspaces.md'
    - 'tasks/data.md'
    - 'tasks/git.md'
  - Scenarios:
    - Extract-Transform-Load:
      - 'scenarios/etl/intro.md'
      - 'scenarios/etl/collect.md'
      - 'scenarios/etl/process.md'
      - 'scenarios/etl/pipeline.md'
      - 'scenarios/etl/expose.md'
    - ML model training:
      - 'scenarios/ml/intro.md'
      - 'scenarios/ml/training.md'
      - 'scenarios/ml/deploy.md'
    - DBT transofrmation:
      - 'scenarios/etl-core/scenario.md'
    - Nefertem validation:
      - 'scenarios/validation/scenario.md'

theme:
  name: material
  custom_dir: custom/
  features:
    - navigation.expand
    - navigation.path
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
