{{- if .Values.embeddedMySql.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "mysql-pv-claim"
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
    application-crd-id: kubeflow-pipelines
{{- with .Values.persistence.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
{{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
