{{- if and (not (index .Values "mlrun-ce" "mlrun" "db" "enabled")) (eq (index .Values "mlrun-ce" "mlrun" "httpDB" "dbType") "mysql") }}
{{- $password := randAlphaNum 24 | nospace | b64enc }}
{{- $username := "mlrun-admin" }}
apiVersion: v1
kind: Secret
metadata:
  name: mlrun-mysql-admin
  annotations:
    "helm.sh/hook": pre-install
stringData:
  rootUser: {{ $username }}
  rootHost: '%'
  rootPassword: {{ $password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mlrun-mysql-user
  annotations:
    "helm.sh/hook": pre-install
stringData:
  key: {{ $username }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mlrun-mysql-pass
  annotations:
    "helm.sh/hook": pre-install
stringData:
  key: {{ $password }}
{{- end }}