{{- if and (not (index .Values "mlrun-ce" "mlrun" "db" "enabled")) (eq (index .Values "mlrun-ce" "mlrun" "httpDB" "dbType") "mysql") }}
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mlrun-mysql-cluster
spec:
  secretName: mlrun-mysql-admin
  instances: 1
  router:
    instances: 1
  tlsUseSelfSigned: true
  podSpec:
    containers:
    - name: mysql
      resources:
        requests:
          memory: "2048Mi"
          cpu: "1800m"
        limits:
          memory: "8192Mi"
          cpu: "3600m"
  datadirVolumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 8Gi
{{- end }}
