{{- if and (not (index .Values "mlrun-ce" "mlrun" "db" "enabled")) (eq (index .Values "mlrun-ce" "mlrun" "httpDB" "dbType") "mysql") }}
apiVersion: mysql.nakamasato.com/v1alpha1
kind: MySQLDB
metadata:
  name: mlrun
spec:
  dbName: mlrun
  mysqlName: mlrun-mysql
---
apiVersion: mysql.nakamasato.com/v1alpha1
kind: MySQLDB
metadata:
  name: model
spec:
  dbName: model_monitoring
  mysqlName: mlrun-mysql
{{- end }}